sharedDir: ".config"
outputDir: "lib"

mergeRules:
  ".gitignore": true
  ".npmignore": true

ignorePatterns:
  ".gitignore": [
    ".env",
    "node_modules/"
  ]
  ".npmignore": [
    ".env",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    "docs/",
    "example/",
    "media/",
    "node_modules/"
  ]

scripts:
  "prepare:docs": "node --experimental-specifier-resolution=node node_modules/.bin/docs-shared-config"
  "prepare": "npm-run-all prepare:*"

dependencies:
  - "npm-run-all"
